In [1]:
import numpy as np

In [2]:
arr = np.array([-1.5, -1.2, 0.0, 2.1, 24.2])
print(arr.shape)

(5,)


In [3]:
arr = [[-1.5, -1.2, 0.0, 2.1, 24.2], [-1.5, -1.2, 0.0, 2.1, 24.2]]
arr = np.array(arr)
print(arr.shape)
print(arr.dtype)

(2, 5)
float64


In [4]:
arr = [['12', -1.2, 0.0, 2.1, 24.2], [-1.5, -1.2, 0.0, 2.1, 24.2]]
arr = np.array(arr)
print(arr.shape)
print(arr.dtype)  # unicode datatypes because of first element '12'

(2, 5)
<U32


In [5]:
arr = [
        [
          [-1.5, -1.2, 0.0, 2.1, 24.2], 
          [-1.5, -1.2, 0.0, 2.1, 24.2]
        ],
        [
          [0, 0, 0.0, 2.1, 24.2], 
          [-1.5, -1.2, 0.0, 2.1, 24.2]
        ]
      ]
arr = np.array(arr)
print(arr.shape, "\n")
print(str(arr[0]), '\n')
print(arr[1])

(2, 2, 5) 

[[-1.5 -1.2  0.   2.1 24.2]
 [-1.5 -1.2  0.   2.1 24.2]] 

[[ 0.   0.   0.   2.1 24.2]
 [-1.5 -1.2  0.   2.1 24.2]]
