In [2]:
import numpy as np

* ### determine shape of each element with dtype

In [24]:
dt = np.dtype((np.int32, (2, 3)))
# the empty tuple which declares the shape is empty thus the empty 
# array has the (2, 3) shape for this non-existing element
print(np.zeros((), dtype=dt))

[[0 0 0]
 [0 0 0]]


In [25]:
dt = np.dtype(np.int32)
print(np.zeros((), dtype=dt))

dt = np.dtype(np.int32, ())  # is the same as above
print(np.zeros((), dtype=dt))

0
0


In [26]:
dt = np.dtype(np.int32)
print(np.zeros((5, 5), dtype=dt))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* ### Note: shape of array is the shape specified and shape of the dtype was added

In [29]:
dt = np.dtype((np.int32, (2, 3)))
print(np.zeros((1, 1), dtype=dt))
print(np.zeros((1, 1), dtype=dt).shape)

[[[[0 0 0]
   [0 0 0]]]]
(1, 1, 2, 3)


* ### really crazy shapes are possible

In [33]:
dt = np.dtype(("i8, (2, 3)f8, f8"), (2, 3))
print(np.zeros((1), dtype=dt))
print(np.zeros((1), dtype=dt).shape)

[(0, [[0., 0., 0.], [0., 0., 0.]], 0.)]
(1,)
