In [1]:
import numpy as np

## slicing

In [4]:
arr = np.array([-1.5, -1.2, 0.0, 2.1, 24.2, 5.0, 13.3, 12.3])
print(arr[0])
print(arr[1:7])
print(arr[1:7:2])
print(arr[::-1])

-1.5
[-1.2  0.   2.1 24.2  5.  13.3]
[-1.2  2.1  5. ]
[12.3 13.3  5.  24.2  2.1  0.  -1.2 -1.5]


## indexing

In [5]:
arr = [
        [
          [-1.0, -1.2, 0.0, 2.1, 24.2], 
          [-2.0, -1.2, 0.0, 2.1, 24.2],
          [-3.0, -1.2, 0.0, 2.1, 24.2]
        ],
        [
          [4.0, 0, 0.0, 2.1, 24.2], 
          [5.0, -1.2, 0.0, 2.1, 24.2],
          [6.0, -1.2, 0.0, 2.1, 24.2]
        ],
        [
          [7.0, 0, 0.0, 2.1, 24.2], 
          [8.0, -1.2, 0.0, 2.1, 24.2],
          [9.0, -1.2, 0.0, 2.1, 24.2]
        ]
      ]
np_temp = np.array(arr)
print(np_temp.shape)

(3, 3, 5)


In [48]:
row = [[0, 1], [2, 1]]  # first value of row corresponds to first value of column
column = [[0, 1], [2, 2]]
print(np_temp[row, column])

[[[-1.  -1.2  0.   2.1 24.2]
  [ 5.  -1.2  0.   2.1 24.2]]

 [[ 9.  -1.2  0.   2.1 24.2]
  [ 6.  -1.2  0.   2.1 24.2]]]
