In [1]:
import numpy as np

* ### np arrays behave like vectors. Basic operations like +, -, *, /, **

In [2]:
A = np.array([
              [1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]
            ])
B = np.array([
              [1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]
            ])

In [4]:
print(A*B, '\n')  # is in numpy not the real matrix multiplication
print(np.dot(A, B))  # real matrix multiplication

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


* ### logic

In [6]:
print(A==B, '\n')  # element wise

F = np.array([[True, True, False], [False, False, True], [True, True, True]])
G = np.array([[False, True, False], [False, True, False], [True, True, False]])

print(np.logical_or(F, G), '\n')
print(np.logical_and(F, G))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 

[[ True  True False]
 [False  True  True]
 [ True  True  True]] 

[[False  True False]
 [False False False]
 [ True  True False]]


* ### matrix & vector

In [11]:
a = np.array([1, 2, 3])
print(a*A, '\n')  # broadcasting
print(a+A, '\n')  # broadcasting

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]] 

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]] 



* ### transpose on vectors does not work like is should do

In [12]:
print(a.transpose()*A, '\n')
print(a.transpose(), '\n')  # tanspose did not change the array

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]] 

[1 2 3] 



* ### need to convert vector to matrix and adjust shape to matrix, then transpose works

In [22]:
a = np.array([[1, 2, 3]]*3).transpose()
print(a, '\n')
print(a*A, '\n')

# alternative, create column vector by creating 2d matrix and transpose
print(np.array([[1, 2, 3]]).transpose()*A)

[[1 1 1]
 [2 2 2]
 [3 3 3]] 

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]] 

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
