In [1]:
import numpy as np

In [ ]:
A = np.array([
              [1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]
            ])

## flatten & ravel both flatten the array
* ### flatten: allocates new space 
* ### ravel: overrides existing space thus ravel is faster

In [8]:
print(A.flatten(order="C"))  # C: by row, F: by column, A: do whatever np did before
print(A.ravel(order="F"))
print(all(A.ravel()==A.flatten()))  # identical

[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
True


## reshape

In [9]:
shape = np.array(range(24))
print(shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [14]:
print(shape.reshape(12,2), "\n")
print(A.reshape(A.size), "\n")  # flatten also possible
print(A.reshape(-1))  # alternative for flatten

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9]
