In [1]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

## stack

In [8]:
# also with matrices possible
print(np.row_stack((a, b)), "\n")
print(np.column_stack((a, b)), "\n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 



## concatenate

In [14]:
print(np.concatenate((a, b), axis=0), "\n")  # axis: 0=row, 1=column

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.concatenate((A, B), axis=0), "\n")
print(np.concatenate((A, B), axis=1), "\n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]] 



In [15]:
A = np.array([[[1, 2]], [[3, 4]]])
B = np.array([[[5, 6]], [[7, 8]]])

print(np.concatenate((A, B), axis=0), '\n--------------')
print(np.concatenate((A, B), axis=1), '\n--------------')        
print(np.concatenate((A, B), axis=2), '\n') 

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]] 
--------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] 
--------------
[[[1 2 5 6]]

 [[3 4 7 8]]] 



## tile
* ### is a form of padding where the original array will be used as values. <br>(2, 3) means fit 2 original array 2 times vertically & 3 times horizontally

In [19]:
A = np.array([[1, 2], [3, 4]])
print(np.tile(A, (2, 3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## padding
* ### a way to enhance the shape and fill the blanks here in this case with zeros

In [20]:
res = np.zeros((50, 50))
res[:A.shape[0], :A.shape[1]] = A
print(res)

[[1. 2. 0. ... 0. 0. 0.]
 [3. 4. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
