In [4]:
import numpy as np
from numpy.random import choice, randint, binomial

## choice

In [5]:
a = np.array(['A', 'B', 'C'])
ps = [0.2, 0.5, 0.3]  # add up to 1
# generates random sample given a sample & weight
print(choice(a, size=(5, 10), p=ps))

[['C' 'B' 'A' 'C' 'C' 'A' 'B' 'B' 'C' 'B']
 ['B' 'B' 'C' 'A' 'C' 'C' 'B' 'B' 'B' 'B']
 ['B' 'B' 'B' 'B' 'B' 'B' 'A' 'B' 'B' 'C']
 ['C' 'C' 'A' 'C' 'B' 'B' 'A' 'B' 'C' 'B']
 ['B' 'C' 'A' 'B' 'A' 'C' 'A' 'B' 'C' 'C']]


## randint

In [7]:
print(randint(1, 41, size=(3, 3)))

[[32 34 26]
 [ 1 17 17]
 [34 15 36]]


## binomial distribution

In [8]:
print(binomial(100, 0.3, (50)))

[30 28 32 26 33 35 28 30 27 32 33 31 31 33 36 31 25 37 34 37 21 32 30 34
 34 24 26 26 38 29 34 32 38 25 34 36 29 27 25 34 31 25 26 33 28 33 28 34
 23 29]
