In [3]:
import numpy as np
from numpy.random import randint

In [6]:
A = randint(1, 100, size=(3, 4))
print(A)

np.savetxt("12_test_save.csv", A, fmt='%u', delimiter=',')
#  fmt: format, standard is '%.18e' => 18 digits after comma
# delimeter: stanard is ' '  

B = np.loadtxt('12_test_save.csv', delimiter=',', dtype=np.int32)
print(B)

[[22 64 63 94]
 [49 79 86 16]
 [76 82 58 63]]
[[22 64 63 94]
 [49 79 86 16]
 [76 82 58 63]]
