In [1]:
import numpy as np

In [8]:
print(np.zeros((2, 2)))

[[0. 0.]
 [0. 0.]]


In [9]:
print(np.ones((2, 2)))

[[1. 1.]
 [1. 1.]]


In [3]:
print(np.arange(-13, 56, 7))  # last parameter step size

[-13  -6   1   8  15  22  29  36  43  50]


In [4]:
print(np.linspace(-13, 56, 15))  # last parameter array size

[-13.          -8.07142857  -3.14285714   1.78571429   6.71428571
  11.64285714  16.57142857  21.5         26.42857143  31.35714286
  36.28571429  41.21428571  46.14285714  51.07142857  56.        ]


In [5]:
print(np.full((2, 5), 42))  # last parameter which number to fill array

[[42 42 42 42 42]
 [42 42 42 42 42]]


In [6]:
print(np.eye(42))  # identity matrix

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [7]:
print(np.random.random((2, 3)))

[[0.7977914  0.43868242 0.05569908]
 [0.21794653 0.65217598 0.88008857]]
