In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

In [3]:
print(np.sin(A))
print(np.exp(A))   # e^A
print(np.exp2(A))  # 2^A
print(np.power(A, 3))  # A^3
print(np.log(A))  # ln(V)
print(np.log2(A))  # log_2(V)
print(np.log10(A))  

[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 1  8 27]
[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]


In [5]:
print(np.argmax(A))  # get index of biggest element

2


In [6]:
ran = np.random.random(10)
print(ran)

[0.92779681 0.65784212 0.72439296 0.50029053 0.31852339 0.74608786
 0.00349379 0.88035863 0.20956064 0.5100936 ]


In [7]:
# returns sorted array in which elements are the indexes of original array 
print(np.argsort(ran))

[6 8 4 3 9 1 2 5 7 0]


In [8]:
# add at specific indexes, here is normal addition with +1
np.add.at(ran, [x for x in range(10)], 1)
print(ran)

# here add every 2nd element by 1
np.add.at(ran, [x for x in range(0, 10, 2)], 1) 
print(ran)

[1.92779681 1.65784212 1.72439296 1.50029053 1.31852339 1.74608786
 1.00349379 1.88035863 1.20956064 1.5100936 ]
[2.92779681 1.65784212 2.72439296 1.50029053 2.31852339 1.74608786
 2.00349379 1.88035863 2.20956064 1.5100936 ]
